---
- name: Aggregates all specific playbooks (meta playbook)
  hosts: lustre_nodes
  become: yes
  gather_facts: yes

  tasks:
    # Tasks for SELinux disablement
    - import_tasks: tasks/selinux.yml
    # Tasks for system registration.
    - import_tasks: tasks/registration.yml
    # Tasks for NTP configuration
    - import_tasks: tasks/ntp-setup.yml
    # Tasks for configuring HA
    - import_tasks: tasks/heartbeat.yml
    - import_tasks: tasks/ha-setup.yml
    - import_tasks: tasks/ha-hooks-setup.yml
    #
    # Tasks for configuring Infiniband interfaces
    - import_tasks: tasks/ib-setup.yml
    #
    # Tasks for configuring Lnet
    - import_tasks: tasks/lnet-setup.yml
    # Tasks for installing Lustre software
    #
    # Tasks for configuring Luste filesystems and services
    - import_tasks: tasks/lustre-storage.yml

  handlers:
    - import_tasks: handlers/handlers.yml
