---
- name: Generate lnet interface configuration from template
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "755"
  loop:
    - { src: "../templates/etc/lnet.conf.j2", dest: "/etc/lnet.conf" }
